services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=dapr
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=auth

  redis:
    image: redis:8.2.4-alpine
    command: [ "redis-server", "--save", "" ]
  placement:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  # Arbiter
  arbiter-service:
    build: .
    ports:
      - "3500:3500"
    environment:
      - ROLE=arbiter
      - DAPR_HTTP_ENDPOINT=http://arbiter-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://arbiter-sidecar:50001
    depends_on:
      - redis
      - placement
  arbiter-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "arbiter-service",
        "--app-port", "3000",
        "--app-channel-address", "arbiter-service",
        "--placement-host-address", "placement:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - arbiter-service

  # smoker 0
  smoker-0-service:
    build: .
    ports:
      - "3501:3500"
    environment:
      - ROLE=smoker
      - DAPR_HTTP_ENDPOINT=http://smoker-0-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://smoker-0-sidecar:50001
      - SMOKER_ID=smoker-0
    depends_on:
      - redis
      - placement
  smoker-0-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "smoker-0-service",
        "--app-port", "3000",
        "--app-channel-address", "smoker-0-service",
        "--placement-host-address", "placement:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - smoker-0-service

  # smoker 1
  smoker-1-service:
    build: .
    ports:
      - "3502:3500"
    environment:
      - ROLE=smoker
      - DAPR_HTTP_ENDPOINT=http://smoker-1-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://smoker-1-sidecar:50001
      - SMOKER_ID=smoker-1
    depends_on:
      - redis
      - placement
  smoker-1-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "smoker-1-service",
        "--app-port", "3000",
        "--app-channel-address", "smoker-1-service",
        "--placement-host-address", "placement:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - smoker-1-service

  # smoker 2
  smoker-2-service:
    build: .
    ports:
      - "3503:3500"
    environment:
      - ROLE=smoker
      - DAPR_HTTP_ENDPOINT=http://smoker-2-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://smoker-2-sidecar:50001
      - SMOKER_ID=smoker-2
    depends_on:
      - redis
      - placement
  smoker-2-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "smoker-2-service",
        "--app-port", "3000",
        "--app-channel-address", "smoker-2-service",
        "--placement-host-address", "placement:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - smoker-2-service