services:
  redis:
    image: redis:8.2.4-alpine
    command: [ "redis-server", "--save", "" ]

  # Sink
  placement-sink:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  sink:
    build: .
    environment:
      - ROLE=sink
      - DAPR_HTTP_ENDPOINT=http://sink-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://sink-sidecar:50001
    volumes:
      - ./metrics_sink:/metrics
    depends_on:
      - redis
      - placement-sink
  sink-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "sink",
        "--app-port", "3000",
        "--app-channel-address", "sink",
        "--placement-host-address", "placement-sink:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - sink

  # big 0
  placement-w0:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w0:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w0-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w0-sidecar:50001
      - BIG_ID=w0
    volumes:
      - ./metrics_w0:/metrics
    depends_on:
      - redis
      - placement-w0
  w0-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w0",
        "--app-port", "3000",
        "--app-channel-address", "w0",
        "--placement-host-address", "placement-w0:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w0

  # big 1
  placement-w1:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w1:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w1-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w1-sidecar:50001
      - BIG_ID=w1
    volumes:
      - ./metrics_w1:/metrics
    depends_on:
      - redis
      - placement-w1
  w1-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w1",
        "--app-port", "3000",
        "--app-channel-address", "w1",
        "--placement-host-address", "placement-w1:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w1

  # big 2
  placement-w2:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w2:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w2-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w2-sidecar:50001
      - BIG_ID=w2
    volumes:
      - ./metrics_w2:/metrics
    depends_on:
      - redis
      - placement-w2
  w2-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w2",
        "--app-port", "3000",
        "--app-channel-address", "w2",
        "--placement-host-address", "placement-w2:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w2

  # big 3
  placement-w3:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w3:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w3-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w3-sidecar:50001
      - BIG_ID=w3
    volumes:
      - ./metrics_w3:/metrics
    depends_on:
      - redis
      - placement-w3
  w3-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w3",
        "--app-port", "3000",
        "--app-channel-address", "w3",
        "--placement-host-address", "placement-w3:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w3

  # big 4
  placement-w4:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w4:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w4-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w4-sidecar:50001
      - BIG_ID=w4
    volumes:
      - ./metrics_w4:/metrics
    depends_on:
      - redis
      - placement-w4
  w4-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w4",
        "--app-port", "3000",
        "--app-channel-address", "w4",
        "--placement-host-address", "placement-w4:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w4

  # big 5
  placement-w5:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w5:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w5-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w5-sidecar:50001
      - BIG_ID=w5
    volumes:
      - ./metrics_w5:/metrics
    depends_on:
      - redis
      - placement-w5
  w5-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w5",
        "--app-port", "3000",
        "--app-channel-address", "w5",
        "--placement-host-address", "placement-w5:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w5

  # big 6
  placement-w6:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w6:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w6-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w6-sidecar:50001
      - BIG_ID=w6
    volumes:
      - ./metrics_w6:/metrics
    depends_on:
      - redis
      - placement-w6
  w6-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w6",
        "--app-port", "3000",
        "--app-channel-address", "w6",
        "--placement-host-address", "placement-w6:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w6

  # big 7
  placement-w7:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w7:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w7-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w7-sidecar:50001
      - BIG_ID=w7
    volumes:
      - ./metrics_w7:/metrics
    depends_on:
      - redis
      - placement-w7
  w7-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w7",
        "--app-port", "3000",
        "--app-channel-address", "w7",
        "--placement-host-address", "placement-w7:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w7

  # big 8
  placement-w8:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w8:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w8-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w8-sidecar:50001
      - BIG_ID=w8
    volumes:
      - ./metrics_w8:/metrics
    depends_on:
      - redis
      - placement-w8
  w8-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w8",
        "--app-port", "3000",
        "--app-channel-address", "w8",
        "--placement-host-address", "placement-w8:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w8

  # big 9
  placement-w9:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w9:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w9-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w9-sidecar:50001
      - BIG_ID=w9
    volumes:
      - ./metrics_w9:/metrics
    depends_on:
      - redis
      - placement-w9
  w9-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w9",
        "--app-port", "3000",
        "--app-channel-address", "w9",
        "--placement-host-address", "placement-w9:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w9

  # big 10
  placement-w10:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w10:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w10-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w10-sidecar:50001
      - BIG_ID=w10
    volumes:
      - ./metrics_w10:/metrics
    depends_on:
      - redis
      - placement-w10
  w10-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w10",
        "--app-port", "3000",
        "--app-channel-address", "w10",
        "--placement-host-address", "placement-w10:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w10

  # big 11
  placement-w11:
    image: daprio/placement:1.16.0
    command: [ "./placement", "--port", "50006" ]
  w11:
    build: .
    environment:
      - ROLE=big
      - DAPR_HTTP_ENDPOINT=http://w11-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w11-sidecar:50001
      - BIG_ID=w11
    volumes:
      - ./metrics_w11:/metrics
    depends_on:
      - redis
      - placement-w11
  w11-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "w11",
        "--app-port", "3000",
        "--app-channel-address", "w11",
        "--placement-host-address", "placement-w11:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components:/components
    depends_on:
      - w11