services:
  redis:
    image: redis:8.2.4-alpine

  placement:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]

  arbitrator:
    build: .
    environment:
      - ROLE=arbitrator
      - NUMBER_OF_PHILOSOPHERS=6
      - DAPR_HTTP_ENDPOINT=http://arbitrator-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://arbitrator-sidecar:50001
      - METRICS_DIRECTORY=/metrics
    depends_on:
      - arbitrator-sidecar
    volumes:
      - "./output/arbitrator/metrics:/metrics"

  arbitrator-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "arbitrator-sidecar",
      "--app-channel-address", "arbitrator",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  w0:
    build: .
    environment:
      - PHILOSOPHER_ID=0
      - DAPR_HTTP_ENDPOINT=http://w0-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w0-sidecar:50001
      - METRICS_DIRECTORY=/metrics
    depends_on:
      - w0-sidecar
    volumes:
      - "./output/w0/metrics:/metrics"

  w0-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w0-sidecar",
      "--app-channel-address", "w0",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement0:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  placement0:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]

  w1:
    build: .
    environment:
      - PHILOSOPHER_ID=1
      - DAPR_HTTP_ENDPOINT=http://w1-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w1-sidecar:50001
      - METRICS_DIRECTORY=/metrics
    depends_on:
      - w1-sidecar
    volumes:
      - "./output/w1/metrics:/metrics"

  w1-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w1-sidecar",
      "--app-channel-address", "w1",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement1:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  placement1:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]

  w2:
    build: .
    environment:
      - PHILOSOPHER_ID=2
      - DAPR_HTTP_ENDPOINT=http://w2-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w2-sidecar:50001
      - METRICS_DIRECTORY=/metrics
    depends_on:
      - w2-sidecar
    volumes:
      - "./output/w2/metrics:/metrics"

  w2-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w2-sidecar",
      "--app-channel-address", "w2",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement2:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  placement2:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]

  w3:
    build: .
    environment:
      - PHILOSOPHER_ID=3
      - DAPR_HTTP_ENDPOINT=http://w3-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w3-sidecar:50001
      - METRICS_DIRECTORY=/metrics
    depends_on:
      - w3-sidecar
    volumes:
      - "./output/w3/metrics:/metrics"

  w3-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w3-sidecar",
      "--app-channel-address", "w3",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement3:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  placement3:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]

  w4:
    build: .
    environment:
      - PHILOSOPHER_ID=4
      - DAPR_HTTP_ENDPOINT=http://w4-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w4-sidecar:50001
      - METRICS_DIRECTORY=/metrics
    depends_on:
      - w4-sidecar
    volumes:
      - "./output/w4/metrics:/metrics"

  w4-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w4-sidecar",
      "--app-channel-address", "w4",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement4:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  placement4:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]

  w5:
    build: .
    environment:
      - PHILOSOPHER_ID=5
      - DAPR_HTTP_ENDPOINT=http://w5-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://w5-sidecar:50001
      - METRICS_DIRECTORY=/metrics
    depends_on:
      - w5-sidecar
    volumes:
      - "./output/w5/metrics:/metrics"

  w5-sidecar:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "w5-sidecar",
      "--app-channel-address", "w5",
      "--app-port", "3000",
      "--resources-path", "/components",
      "--placement-host-address", "placement5:50006",
    ]
    volumes:
      - "./redis/components:/components"
    depends_on:
      - redis

  placement5:
    image: "daprio/placement:edge"
    command: [ "./placement", "--port", "50006" ]