services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=dapr
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=auth
    networks:
      - influx-net

  redis:
    image: redis:8.2.4-alpine
    networks:
      - broker-net

  redis-a:
    image: redis:8.2.4-alpine
    networks:
      - cluster-a

  placement-a:
    image: daprio/placement:1.16.0
    command: ["./placement", "--port", "50006"]
    networks:
      - cluster-a

  producer-service:
    build: .
    ports:
      - "3500:3500"
    environment:
      - ROLE=producer
      - DAPR_HTTP_ENDPOINT=http://producer-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://producer-sidecar:50001
    networks:
      - cluster-a
      - influx-net
    depends_on:
      - redis
      - redis-a
      - placement-a

  producer-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "producer-service",
        "--app-port", "3000",
        "--app-channel-address", "producer-service",
        "--placement-host-address", "placement-a:50006",
        "--resources-path", "/components",
        "--log-level", "warn",
      ]
    volumes:
      - ./redis/components-redis-producer:/components
    networks:
      - broker-net
      - cluster-a
    depends_on:
      - producer-service

  redis-b:
    image: redis:8.2.4-alpine
    networks:
      - cluster-b

  placement-b:
    image: daprio/placement:1.16.0
    command: ["./placement", "--port", "50006"]
    networks:
      - cluster-b

  counter-service:
    build: .
    environment:
      - ROLE=counter
      - DAPR_HTTP_ENDPOINT=http://counter-sidecar:3500
      - DAPR_GRPC_ENDPOINT=http://counter-sidecar:50001
    networks:
      - cluster-b
      - influx-net
    depends_on:
      - redis
      - redis-b
      - placement-b

  counter-sidecar:
    image: daprio/daprd:1.16.0
    command:
      [
        "./daprd",
        "--app-id", "counter-service",
        "--app-port", "3000",
        "--app-channel-address", "counter-service",
        "--placement-host-address", "placement-b:50006",
        "--resources-path", "/components",
        "--log-level", "info",
      ]
    volumes:
      - ./redis/components-redis-counter:/components
    networks:
      - broker-net
      - cluster-b
    depends_on:
      - counter-service

networks:
  cluster-a:
  cluster-b:
  broker-net:
  influx-net: